# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_model_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='topics/%Y/%m/%d/'),
        ),
    ]
