# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170421_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='docfile',
            field=models.ImageField(upload_to='images/blog/%Y/%m/%d'),
        ),
    ]
